# https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift
name: Swift

on: [push]

jobs:
    build:
        runs-on: macos-latest

        steps:
            - uses: actions/checkout@v2
            - uses: fwal/setup-swift@v1
            - name: Build
              run: swift build
            - name: Run tests
              run: swift test
