# https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on: [push]

jobs:
    build:
        name: Swift ${{ matrix.swift }} on ${{ matrix.os }}
        strategy:
            matrix:
                os: [ubuntu-latest, macos-latest]
                swift: ["5.5", "5.3"]
        runs-on: ${{ matrix.os }}
        steps:
            - uses: actions/checkout@v2
            - uses: fwal/setup-swift@d43a564349d1341cd990cfbd70d94d63b8899475
              with:
                  swift-version: "5.3.3"
            - name: Build
              run: swift build
            - name: Run tests
              run: swift test
