# https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift
name: Swift

on: [push]

jobs:
    build:
        runs-on: macos-latest
        strategy:
            matrix:
                os: [macos-latest]
                swift: ["5.5"]
        steps:
            - uses: actions/checkout@v2
            - name: Build
              run: swift build
            - name: Run tests
              run: swift test
